### ISSUE TITLE
Crash in ConsentActivity.onCreate

### ISSUE THREAD

**Issue by yanzhanghiq** [heremaps/here-sdk-examples#295] opened 2023-12-19 13:02 UTC
Device: Nexus 5X 
Android OS version: Android 11
Here SDK version: Heresdk-navigate-android: 4.16.2

Where it happened:
in com.here.sdk.conset  ConsentActivity.java:152

Exception:
java.lang.UnsupportedOperationException - Can't convert value at index 0 to dimension: type=<address>

Crash log:
```

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.x.x.x/com.here.sdk.consent.ConsentActivity}: android.view.InflateException: Binary XML file line #39 in x.x.x:layout/activity_consent: Binary XML file line #39 in x.x.x:layout/activity_consent: Error inflating class android.widget.TextView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7656)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by HERE-SDK-Support-Team** [comment] 2023-12-20 08:57
@yanzhanghiq, thanks raising. We created a ticket #22847. Closing the request, since this is not related to the example reprository, but we will inform on any progress on the issue in this thread. Hope this helps.

**Closed by HERE-SDK-Support-Team** 2023-12-20 08:57 UTC

**Comment by HERE-SDK-Support-Team** [comment] 2024-01-10 16:35
@yanzhanghiq Unfortunately, we could not reproduce the issue. If you can provide more information how to replicate the issue, we can have another look. Thanks.
