### ISSUE TITLE
MapUpdater updateCatalog ~ 1 minute to finish update after 100% success.

### ISSUE THREAD

**Issue by samvmisti** [heremaps/here-sdk-examples#215] opened 2023-01-25 14:36 UTC
Hi, HERE team!

I've reproduced it several times.

Countries: Lithuania and Latvia. Region ids - 20633737, 20633740.

From MapUpdater call method updateCatalog()

**When** the last map is updated and has a percentage 100% (CatalogUpdateProgressListener - `onProgress`) 

**Then** I should wait ~1 minute for onComplete. (CatalogUpdateProgressListener - `onComplete`)

**Expected** - I receive onComplete callback immediately.

Is this an expected behavior or a bug?

heresdk-navigate-android-4.13.0.0.10488

**Comment by datasun** [comment] 2023-01-30 16:56
Thanks for the detailed steps.

This is a known issue. We track it internally here #13800.

**Comment by romandanylyk** [comment] 2023-02-01 11:57
I'm experiencing this as well,
looks like at this point it is expected behavior since once the update is downloaded, it has to be replaced. Meaning the old map packages are removed and the new ones remain. This is probably why it is taking some extra time after the progress has reached 100%.

@datasun do you have any insights on when this issue could be fixed?

**Comment by HERE-SDK-Support-Team** [comment] 2023-02-02 18:22
@romandanylyk, this is exactly what is happening. We'll try to improve this for one of the next releases, so that the progress will increase more fluently and is better reflecting what is going on. Unfortunately, we cannot give a more precise due date yet.

**Comment by HERE-SDK-Support-Team** [comment] 2023-12-20 11:13
This issue has been resolved with 4.17.x - closing. Please leave a reply, in case it is still occurring. Thanks!

**Closed by HERE-SDK-Support-Team** 2023-12-20 11:13 UTC
