### ISSUE TITLE
32-bit so report error

### ISSUE THREAD

**Issue by Zengyonghao** [heremaps/here-sdk-examples#61] opened 2021-02-02 02:47 UTC
I only pack the ARM64-V8A, everything works fine

But if I just pack Armeabi-V7 I will get an error
![image](https://user-images.githubusercontent.com/17347430/106545199-eab6e100-6543-11eb-9a30-d9cf298c41b0.png)

I tested this on multiple phones and found the same result

**Comment by datasun** [comment] 2021-02-02 20:55
The HERE SDK for Android supports Android 32-bit devices with x86 or ARMv7 architecture _and_ 64-bit devices with x86_64 or ARM64/v8 architecture.

Can you provide some more details which devices you have tested? Also, we do not recommend to exclude undesired architectures like it was done for the Premium Edition. Do you have a specific need to do so? Thanks.

**Comment by Zengyonghao** [comment] 2021-02-03 07:49
> The HERE SDK for Android supports Android 32-bit devices with x86 or ARMv7 architecture _and_ 64-bit devices with x86_64 or ARM64/v8 architecture.
> 
> Can you provide some more details which devices you have tested? Also, we do not recommend to exclude undesired architectures like it was done for the Premium Edition. Do you have a specific need to do so? Thanks.

I use all phones with ARM-64 CPUs,This is a problem I found by accident。

**Comment by datasun** [comment] 2021-02-03 16:10
Thanks! So, if I understand correctly, you used the split ABI feature to run on ARM64/v8 devices with ARMv7 builds? Of course, this would _not_ work, as those devices require 64-bit binaries.

**Comment by Zengyonghao** [comment] 2021-02-04 07:44
> Thanks! So, if I understand correctly, you used the split ABI feature to run on ARM64/v8 devices with ARMv7 builds? Those devices run well with 64-bit binaries, but they also still should support the older ARMv7, if I am not wrong. How exactly did you removed the 64-bit architectures?
> 
> PS: From the stack trace it looks like you are running out of memory. If you could paste the stack trace as text, we could try to symbolize it to see where this happens.

![image](https://user-images.githubusercontent.com/17347430/106859899-a58ade80-66fe-11eb-9cc3-07a21d98603c.png)
I use the gradle configuration to package the apk and get the v7a apk
![image](https://user-images.githubusercontent.com/17347430/106860368-3feb2200-66ff-11eb-83af-4f14aeef754c.png)
2021-02-04 15:40:18.245 15701-15701/? A/DEBUG: pid: 21330, tid: 15697, name: Thread-59  >>> cn.com.xxxx.atlas <<<
2021-02-04 15:40:18.245 15701-15701/? A/DEBUG: uid: 10876
2021-02-04 15:40:18.245 15701-15701/? A/DEBUG: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
2021-02-04 15:40:18.245 15701-15701/? A/DEBUG: Abort message: '/usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type std::bad_alloc: std::bad_alloc" failed'
2021-02-04 15:40:18.245 15701-15701/? A/DEBUG:     r0  00000000  r1  00003d51  r2  00000006  r3  b6ccb460
2021-02-04 15:40:18.245 15701-15701/? A/DEBUG:     r4  b6ccb474  r5  b6ccb458  r6  00005352  r7  0000016b
2021-02-04 15:40:18.245 15701-15701/? A/DEBUG:     r8  b6ccb470  r9  b6ccb460  r10 b6ccb490  r11 b6ccb480
2021-02-04 15:40:18.245 15701-15701/? A/DEBUG:     ip  00003d51  sp  b6ccb430  lr  e6ea367f  pc  e6ea3692
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG: backtrace:
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #00 pc 00061692  /apex/com.android.runtime/lib/bionic/libc.so (abort+166) (BuildId: 4147742bd3d173f43df099be13045b81)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #01 pc 00061ba7  /apex/com.android.runtime/lib/bionic/libc.so (__assert2+22) (BuildId: 4147742bd3d173f43df099be13045b81)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #02 pc 00959e19  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #03 pc 00959f19  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #04 pc 00958371  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #05 pc 00957c1f  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #06 pc 00957be7  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #07 pc 009536af  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #08 pc 005a69cb  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #09 pc 005a699d  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #10 pc 005e090b  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #11 pc 005e00f3  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #12 pc 005dffad  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #13 pc 005e2b77  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #14 pc 005e2ae5  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #15 pc 005de833  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #16 pc 00602a33  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #17 pc 006102f3  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #18 pc 005d56b7  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #19 pc 005d53b3  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #20 pc 005d5495  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #21 pc 00406475  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #22 pc 00405a27  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #23 pc 00276145  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #24 pc 0027caa5  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #25 pc 0027d649  /data/app/cn.com.xxxx.atlas-hS_nKdw92gPOflnc4cgsEg==/base.apk!libheresdk.so (offset 0xd53000) (BuildId: 44f0ab193d87557c12fb24ee8b0b7f88aeff744e)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #26 pc 000abcdb  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20) (BuildId: 4147742bd3d173f43df099be13045b81)
2021-02-04 15:40:18.248 15701-15701/? A/DEBUG:       #27 pc 00062dc3  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30) (BuildId: 4147742bd3d173f43df099be13045b81)

**Comment by datasun** [comment] 2021-02-04 14:17
Thanks, this looks like the HERE Rendering Engine is running out of memory. Does this also happen when you execute the HelloMap example? From our local tests, the ARMv7 build works fine on 64-bit devices, without any crash. So, it would be good to know if you are running an app that is maybe loading bigger images or something similar.

**Comment by Zengyonghao** [comment] 2021-02-05 03:02
> Thanks, this looks like the HERE Rendering Engine is running out of memory. Does this also happen when you execute the HelloMap example? From our local tests, the ARMv7 build works fine on 64-bit devices, without any crash. So, it would be good to know if you are running an app that is maybe loading bigger images or something similar.

LOL..I used your Hello Map Demo, after filtering the 64-bit so, the same problem occurred
I uploaded the running HelloMap project

**Comment by datasun** [comment] 2021-02-05 08:43
Thanks :) ... that's good, actually, then we can try to reproduce this 1:1 with the same steps and setup you did. I will update this thread once we know more about the root cause.

**Comment by datasun** [comment] 2021-05-06 16:54
@Zengyonghao, we tried to reproduce the issue:

- We took an example app from here with HERE SDK v 4.7.2 (Explore Edition).
- Then built for armeabi-v7a and confirmed that only the armebi-v7a version of libheresdk.so is part of the apk file.
- We also built and ran the current HERE SDK version for armeabi-v7a and did not encounter this problem.

It seems to work as expected. Closing the issue for now. Please comment, if there is something more to check. Thanks!

**Closed by datasun** 2021-05-06 16:54 UTC
