### ISSUE TITLE
HereMaps Explorer error on RoutingEngine CalculateRoute

### ISSUE THREAD

**Issue by yuvaraj119** [heremaps/here-sdk-examples#234] opened 2023-05-02 04:48 UTC
In Heremaps explorer(4.13.4.0.11034 version) when i call RoutingEngine.calculateRoute getting below error.
` AndroidAssetsLoader  E  Failed to load asset stream voice_assets/voice_package_en-US/content/init.lua
                                                                                        java.io.FileNotFoundException: voice_assets/voice_package_en-US/content/init.lua
                                                                                        	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
                                                                                        	at android.content.res.AssetManager.open(AssetManager.java:796)
                                                                                        	at android.content.res.AssetManager.open(AssetManager.java:773)
                                                                                        	at com.here.sdk.core.engine.AndroidAssetsLoader.loadAssetStream(Unknown Source:13)
                                                                                        	at com.here.sdk.core.engine.AndroidAssetsLoader.loadAsset(Unknown Source:5)
                                                                                        	at com.here.sdk.routing.RoutingEngine.calculateRoute(Native Method)`

**Comment by HERE-SDK-Support-Team** [comment] 2023-05-02 07:40
Hi @yuvaraj119, the voice assets are only distributed for the _Navigate Edition_. You can ignore this log message, it is not relevant for the _Explore Edition_. Thanks.

**Comment by yuvaraj119** [comment] 2023-05-02 12:00
I'm using Explorer version and this error is crashing the application.

**Comment by HERE-SDK-Support-Team** [comment] 2023-05-02 12:43
Are you doing any special steps to get the crash? Ie. can you reproduce this with the Routing example app?

**Comment by yuvaraj119** [comment] 2023-05-02 17:22
With Routing example I am not able to reproduce but I'm using the same class in my code without any change to calculate Routing. 
One difference is I'm doing on Jepack compose.

**Comment by HERE-SDK-Support-Team** [comment] 2023-05-02 19:19
The `voice_assets` log is the causing a crash. Can you paste the full log? Also, maybe you can have a look where exactly in your code the crash is happening. Try to clean the code when receiving the route result. Most likely, there is a crash in your code on app side happening when receiving the route result. This is unlikely to be related to JetPack.

**Comment by HERE-SDK-Support-Team** [comment] 2023-05-16 09:34
Closing since there was no update since two weeks. Please leave a comment when you have an update. Thanks!

**Closed by HERE-SDK-Support-Team** 2023-05-16 09:34 UTC

**Comment by HERE-SDK-Support-Team** [comment] 2023-05-19 10:44
Hi @yuvaraj119, 

this error relates to the EV consumption model for ascents. Try to set only `CarOptions`. When you calculate routes for electric vehicles (EV), this is the minimum you have to set (copied from our dev guide):

```
    EVCarOptions evCarOptions = new EVCarOptions();

    // The below three options are the minimum you must specify or routing will result in an error.
    evCarOptions.consumptionModel.ascentConsumptionInWattHoursPerMeter = 9;
    evCarOptions.consumptionModel.descentRecoveryInWattHoursPerMeter = 4.3;
    evCarOptions.consumptionModel.freeFlowSpeedTable = new HashMap<Integer, Double>() {{
        put(0, 0.239);
        put(27, 0.239);
        put(60, 0.196);
        put(90, 0.238);
    }};
````

 Note that `ascentConsumptionInWattHoursPerMeter` must be greater than 0.

**Comment by yuvaraj119** [comment] 2023-05-19 13:07
> Hi @yuvaraj119, 
> 
> this error relates to the EV consumption model for ascents. Try to set only `CarOptions`. When you calculate routes for electric vehicles (EV), this is the minimum you have to set (copied from our dev guide):
> 
> ```
>     EVCarOptions evCarOptions = new EVCarOptions();
> 
>     // The below three options are the minimum you must specify or routing will result in an error.
>     evCarOptions.consumptionModel.ascentConsumptionInWattHoursPerMeter = 9;
>     evCarOptions.consumptionModel.descentRecoveryInWattHoursPerMeter = 4.3;
>     evCarOptions.consumptionModel.freeFlowSpeedTable = new HashMap<Integer, Double>() {{
>         put(0, 0.239);
>         put(27, 0.239);
>         put(60, 0.196);
>         put(90, 0.238);
>     }};
> ````
> 
>  Note that `ascentConsumptionInWattHoursPerMeter` must be greater than 0.

Is there a document which describes these three and what it is about?

**Comment by HERE-SDK-Support-Team** [comment] 2023-05-19 13:36
Yes, the consumption model is described here: https://developer.here.com/documentation/android-sdk-explore/4.14.2.0/dev_guide/topics/routing.html#get-routes-for-electric-vehicles.

**Comment by yuvaraj119** [comment] 2023-05-19 14:58
> Yes, the consumption model is described here: https://developer.here.com/documentation/android-sdk-explore/4.14.2.0/dev_guide/topics/routing.html#get-routes-for-electric-vehicles.

Thanks!
