### ISSUE TITLE
Inconsistent behaviour of the location indicator

### ISSUE THREAD

**Issue by TharaaSab** [heremaps/here-sdk-examples#335] opened 2024-08-16 09:19 UTC
Dears,
We are experiencing an inconsistent behaviour related to location indicator in the map. we are using a custom one and adding it to the visual navigator that has a SpeedBasedCameraBehavior.
Our issue is even though the user is standing still (no user location changes), the cursor moves around the map then comes back to the right position.
Kindly provide us with any suggestions to fix this behaviour.

Best regards,

HERE SDK android navigate edition version: 4.18.4

https://github.com/user-attachments/assets/70d08039-2494-432f-8fbd-823ad6d7aceb

**Comment by HERE-SDK-Support-Team** [comment] 2024-09-02 10:20
Hi @TharaaSab,

this issue has been fixed in our latest release HERE SDK 4.19.5. - it was caused by bearing values with low accuracy. This has been optimized and such imprecise GPS signals are now filter out. 

Please give it a try and if the issue persists, please contact our inhouse support team: https://www.here.com/contact?intref=dev_docum

Hope this helps. Thanks!

**Closed by HERE-SDK-Support-Team** 2024-09-02 10:20 UTC
