### ISSUE TITLE
Android's CameraKeyframeTracks example is not working at API 28 (Android 9.0)

### ISSUE THREAD

**Issue by qshen-wolies** [heremaps/here-sdk-examples#303] opened 2024-02-29 02:23 UTC
SDK version:  `heresdk-navigate-android-4.16.0.0.12759`
Device & Operating System: Pixel 3 Emulator API 28 (Android 9.0)
IDE: Android Studio Hedgehog | 2023.1.1 Patch 1

Step to replicate:
1. Try to launch Camerakeyframetracks example with the above configuration
2. Showing a blank screen

Expect behaviour:
Show the map view successfully

Note: The example works fine if I'm using API 29 ~ API 34 in Android Studio's emulator. I think it will be good to double check if other examples is working under API 28 or below.

Please see the following screenshot and logcat to get more information, thanks.

Screenshot:
<img width="444" alt="Screenshot 2024-02-29 at 1 11 48 pm" src="https://github.com/heremaps/here-sdk-examples/assets/141593917/7e16d7c7-d32c-411c-b0eb-d0de2fe367dd">

Logcat:
[cameraKeyframeTracks_error_api28.txt](https://github.com/heremaps/here-sdk-examples/files/14441985/cameraKeyframeTracks_error_api28.txt)

**Comment by HERE-SDK-Support-Team** [comment] 2024-05-06 16:10
Hi @qshen-wolies, 

we tested Android 28 devices and an emulator configuration with Android 28 and the issue is not reproducible. From the logs we can see that
 
`[ERROR] hsdk-geoviz - Failed to create GraphicsPackage 'OpenGL'`

may seem to indicate that OpenGL is misconfigured for the emulator. Edit your emulator settings via _Settings_ -> _Advanced_ -> _OpenGL ES API level_. If it is set to "Autoselect", try to change it to "Renderer Maximum".

Hope this helps. Closing for now. Please leave a reply if this does not solve the issue for you. Thanks!

**Closed by HERE-SDK-Support-Team** 2024-05-06 16:10 UTC
