### ISSUE TITLE
Here maps and not working on orientation change

### ISSUE THREAD

**Issue by zenyagami** [heremaps/here-sdk-examples#205] opened 2022-12-05 09:17 UTC
Apparently if i use the map to to display the route
`visualNavigator.route = route`
if I rotate the screen with the following settings in the manifest
```xml
<activity
            android:name="app.ui.main.MapActivity"
            android:configChanges="orientation|screenSize|uiMode"
```
it will work correctly and the navigation route is displayed and all works corrrectly, unfortunately doing this, is not always desired, why? I have some layouts that depends of the orientation inside
`layout` and `layout-land` if I keep the roientation change, and I go from portrait to landscape the UI will in landscape will still keep displaying the portrait layout (which is not desired), and I'm using navigation component so I cant just for to replace all the fragments easily.

for the navigation I'm using a singletone instance for the "visual navigation" to keep the listeners from orientation change and user leaving the app, if I "cache" the route and I remove `android:configChanges="orientation|screenSize|uiMode"` the map fragment is re created and I use `again`

```kotlin
visualNavigator?startRendering(mapView)
visualNavigator?.route = route
startLocationUpdates()
```
but doing this teh map will not display the route , the naviation location icon, and even not updating correctly the location position.
Is any way to solve this?

**Comment by samrakchan** [comment] 2022-12-07 06:54
I'm also facing the same problem, in my case the error is 
IllegalStateException: Please call MapView.onCreate() before calling any other MapView methods.
though I have already called onCreate just before accessing mapView.mapScene.loadScene()

There could be a known issue, that's why the sample application has also locked the orientation changes. 
https://github.com/heremaps/here-sdk-examples/blob/master/examples/latest/navigate/android/Navigation/app/src/main/java/com/here/navigation/MainActivity.java 
  setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LOCKED);

**Comment by zenyagami** [comment] 2022-12-07 09:01
There is no info about this in the docs, seems that they just "hid" this part and use locked orientation so the sdk will work but this will not work in several layers, in my case I'm using one single activity pattern so I'm using jetpack navigaiton to display another frgaments but if the screen is rotated from portrait to landscape the views will not "recreate" and keep the portrait views because of "screen orientation" in the manifest.
is any way to solve this?

**Comment by datasun** [comment] 2022-12-08 08:57
Thanks for raising this point. The reason why the example apps exclude handling orientation changes is that this has to be done on app-side, there is no SDK-related mechanism for this.

From our "Get Started" guide: Any content that is added to the `MapView`, such as `MapMarker` items, needs to be added again after a screen orientation change.

This means, if you have added a route and then an orientation change is happening, you need to add the same route instance again to the map. Basically, all content that is added to a map view needs to be added again for the new orientation. The map view does not remember its state when it is "recreated".  Note that `onLoadScene()` is not required to be loaded again, so you only need to listen for orientation changes on app side and populate the map view with the content you had on the previous view.

Hope this helps. Please leave a reply if you need more information or if you experience issues with this. Thanks!

**Comment by datasun** [comment] 2022-12-08 09:07
Yes, you are right. My previous comment relates to a non-guidance scenario. When you use the VisualNavigator, it should be different. We should update the NavigationCustom app to show this behavior. Let me take this as an action point.

**Comment by zenyagami** [comment] 2022-12-08 09:11
Sorry for the confusion, yes I meant when the route/navigation is happening, in a "normal" mode is not big deal, because the app will just recreate and the code should work as the first time the user open the app, but is different with visual navigator, I tried to set to null teh route and recreate the visual navigator every time but in my profiler i checked there is a performance issues doing this and not that smooth, and a lot of extra logic in the "client" side. 
Thanks a lot for the feedback.

**Comment by datasun** [comment] 2022-12-08 11:13
Actually, sorry for the confusion from my side as well. My previous comment was wrong and outdated, I edited it.

In fact, orientation changes should work out of the box. All apps already show this by calling **mapView.onSaveInstanceState(outState)**.  

For VisualNavigator, this should also work, so there is no need to do anything else on top. We just tried the **NavigationQuickStart** app: By default, it does allow orientation changes - and when the screen is rotated, guidance continues and the route is still visible. Same for the **MapItems** example app.

Indeed, the **Navigation** app has a SCREEN_ORIENTATION_LOCKED request, but if this line is removed, it will also work. 

@zenyagami Can you try the **NavigationQuickStart** app, without changing any code: Does it look as expected for you or not? Thanks for the help.

**Comment by zenyagami** [comment] 2022-12-08 11:26
@datasun  actually it does not work, I have a crash, the issue is not `SCREEN_ORIENTATION_LOCKED` the issue is in the AndroidManifest:
the following code
`android:configChanges="orientation|screenSize|screenLayout|keyboardHidden">`
this code avoid the re creation of fragments, which usually is ok of many apps, however, if I want to have a differents layouts for example
values
   ----map_layout.xml
values-land
   ----map_layout.xml

If I want to use the 2 layouts one for landscape and one for portrait if i keep `android:configChanges` in the manifest the layout will be always the one from the orientation I launched the app with, for example
if my device is in landscape and I launch the app, the  `values-land` layout  will be loaded, if I rotate the screen , the layout will be still  from`values-land` , which is not desired.
I find a workaround using in the code `fun onConfigurationChanged()` and remove/re add the fragment with the new ui and works, however this is not working when i have jetpack navigation component and navigating thru several fragments.

@datasun can you please try the *NavigationQuickStart* but instead
```` xml
        <activity android:name=".MainActivity"
                  android:exported="true"
                  android:configChanges="orientation|screenSize|screenLayout|keyboardHidden">
            <intent-filter>
```

replace with this:

```xml
<activity android:name=".MainActivity"
                  android:exported="true"
                  >
```

I just removed  `android:configChanges="orientation|screenSize|screenLayout|keyboardHidden"`

**Comment by abhiditi** [comment] 2022-12-08 13:42
If you remove the `android:configChanges="orientation|screenSize|screenLayout|keyboardHidden"` and add two layouts (one for portrait and one for landscape), you get an error log message as: 
**java.lang.IllegalStateException: Please call MapView.onCreate() before calling any other MapView methods.**

The message clearly says to call MapView.onCreate() before calling any other MapView methods. 

To achieve your use case, Simple solution is to remove —> ` android:configChanges="orientation|screenSize|screenLayout|keyboardHidden"` and add `mapView.onCreate(outState);` to  `onSaveInstanceState` like this:

@Override
protected void onSaveInstanceState(@NonNull Bundle outState) {
mapView.onSaveInstanceState(outState);
mapView.onCreate(outState);
super.onSaveInstanceState(outState);
}

Hope, this solves your issue. Thanks

**Comment by datasun** [comment] 2022-12-08 19:32
@zenyagami Thanks again, the issue is now clear. We'll check this.

**Comment by datasun** [comment] 2022-12-09 09:47
@zenyagami The problem is that in the `Activity's` `onCreate()` this line is called:

`mapView.onCreate(savedInstanceState)`

If you recreate the Activity on screen orientation change, the `Bundle` containing the `savedInstanceState` is pointing to a dead horse, since the HERE SDK was already disposed at that point in time.

If you recreate everything and also initialize the HERE SDK, then also the map view needs to be recreated and you have to call `mapView.onCreate(null)` in the `Activity's` `onCreate()` - this way, after each orientation change, the HERE SDK and the map view are both recreated using the new instance of the HERE SDK.

A smarter solution would be to **not** dispose the HERE SDK when the orientation change happens, for example, by checking if the Activity `isFinishing()` or `isChangingConfigurations()`. As a consequence, inside the Activity's onCreate(), you have to add a flag to check if the bundle is null. If it is not null, the HERE SDK is still alive and the map view can be used with the bundled state. Also, it is important in this case to **not** load the map view again for such a recreation case.

Hope this explains the issue well enough. Closing the case. If you have more questions or if you experience other issues, please leave a reply. 

We'll try to update the example apps for one of the next releases to make such cases more clear. Thanks again for raising this issue.

**Closed by datasun** 2022-12-09 09:47 UTC
